/**
 * StateLicensureDisclaimer.tsx
 *
 * WEB-16: Auto-generated state-licensure disclaimer for Try Pro sites.
 *
 * Renders the output of buildLicensureDisclaimer() from lib/practikahDisclaimer.ts.
 * Bilingual (EN/ES) — switches based on isEs prop (matches router.locale).
 *
 * COUNSEL REVIEW FLAG (T-12-06-08):
 * The disclaimer copy generated by buildLicensureDisclaimer() has NOT yet been
 * reviewed by counsel. Legal sign-off required before public launch.
 * Copy may be edited in practikahDisclaimer.ts without re-architecting this component.
 *
 * Tone: fact-stating, no medical claims, no marketing language.
 * Reference: components/landing/RegulatoryDisclosure.tsx (FROZEN — DO NOT MODIFY).
 */

import { buildLicensureDisclaimer } from '../../../../lib/practikahDisclaimer';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface PhysicianRecord {
  country?: string | null;
  licensed_states?: string[] | null;
  primary_state?: string | null;
  cedula_state?: string | null;
}

interface Props {
  physician: PhysicianRecord;
  isEs: boolean;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export default function StateLicensureDisclaimer({ physician, isEs }: Props) {
  const text = buildLicensureDisclaimer(
    {
      country: physician.country,
      licensedStates: physician.licensed_states,
      primaryState: physician.primary_state,
      cedulaState: physician.cedula_state,
    },
    isEs ? 'es' : 'en',
  );

  return (
    <div className="py-8 px-6">
      <div className="max-w-3xl mx-auto text-center border-t border-deep-charcoal/10 pt-8">
        <p className="font-body text-xs text-body-slate/60 leading-relaxed">
          {text}
        </p>
      </div>
    </div>
  );
}
