/**
 * build-sogo-wave round-trip test — Phase 20 Plan 20-03 Task 1.
 *
 * Verifies the generated wave.js is byte-equal to the Wave primitive's SSR
 * output for all 4 variants. This catches the threat T-20-03-01 (wave.js
 * regenerated from stale Wave.tsx) and T-20-03-03 (local-only step skipped).
 *
 * The test is skipped on machines / CI runners where the sibling
 * mailcow-config repo isn't checked out (e.g. fresh Netlify build).
 */
import { describe, it, expect, beforeAll } from 'vitest';
import { renderToStaticMarkup } from 'react-dom/server';
import { readFileSync, existsSync } from 'fs';
import { execSync } from 'child_process';
import { resolve } from 'path';
import React from 'react';
import { Wave } from '../components/shared/practikah/Wave';
import { WAVE_VARIANTS } from '../components/shared/practikah/Wave.types';

const FRONTEND_ROOT = resolve(__dirname, '..');
const SIBLING_ROOT = resolve(__dirname, '../../mailcow-config');
const WAVE_JS = resolve(SIBLING_ROOT, 'sogo/wave.js');
const SIBLING_AVAILABLE = existsSync(SIBLING_ROOT);

describe('build-sogo-wave', () => {
  beforeAll(() => {
    if (!SIBLING_AVAILABLE) return;
    execSync('npm run build:sogo-wave', {
      cwd: FRONTEND_ROOT,
      stdio: 'inherit',
    });
  });

  it.runIf(SIBLING_AVAILABLE)('emits the expected IIFE wrapper', () => {
    const content = readFileSync(WAVE_JS, 'utf8');
    expect(content.startsWith('/* AUTOGENERATED')).toBe(true);
    expect(content.trimEnd().endsWith('})(window);')).toBe(true);
  });

  WAVE_VARIANTS.forEach((variant) => {
    it.runIf(SIBLING_AVAILABLE)(
      `round-trips ${variant} byte-equally to Wave SSR`,
      () => {
        const content = readFileSync(WAVE_JS, 'utf8');
        const expected = renderToStaticMarkup(
          React.createElement(Wave, { variant }),
        );
        // wave.js stores each SVG as a JSON-encoded string value in the
        // MK_WAVE_VARIANTS object literal — it must be findable verbatim.
        expect(content).toContain(JSON.stringify(expected));
      },
    );
  });

  it.runIf(SIBLING_AVAILABLE)(
    'is a pure browser IIFE (no imports / requires)',
    () => {
      const content = readFileSync(WAVE_JS, 'utf8');
      expect(content).not.toMatch(/\brequire\s*\(/);
      expect(content).not.toMatch(/^\s*import\s/m);
    },
  );

  it.runIf(SIBLING_AVAILABLE)(
    'declares all 4 expected variant keys',
    () => {
      const content = readFileSync(WAVE_JS, 'utf8');
      for (const variant of WAVE_VARIANTS) {
        expect(content).toContain(`"${variant}"`);
      }
    },
  );
});
