// AUTOGENERATED at: scripts/build-design-tokens-cjs.ts
// Reads lib/design-tokens.ts and emits lib/design-tokens.cjs so that
// tailwind.config.js (CommonJS) can `require` the same token object the
// TypeScript runtime imports. Runs on `predev` and `prebuild` per
// package.json (Pitfall 1: both lifecycles must regenerate the shim).
//
// Pure JSON.stringify — no React, no renderToStaticMarkup.

import { writeFileSync } from 'fs';
import { tokens } from '../lib/design-tokens';

const out = `// AUTOGENERATED — do not edit. Source: lib/design-tokens.ts
// Regenerated on every npm prebuild + predev. Gitignored.
module.exports = ${JSON.stringify(tokens, null, 2)};
`;
writeFileSync('lib/design-tokens.cjs', out);
console.log('✓ lib/design-tokens.cjs regenerated from lib/design-tokens.ts');
