/**
 * build-sogo-wave — Phase 20 Plan 20-03.
 *
 * SSR the canonical Wave React primitive into a plain-JS IIFE that exposes
 * `window.MK_WAVE_VARIANTS = { darkDesktop, darkMobile, lightDesktop, lightMobile }`,
 * and emit it to ../mailcow-config/sogo/wave.js.
 *
 * Pattern: D-04 + RESEARCH Pattern 4. Local-only build step (RESEARCH
 * Pitfall 2) — mailcow-config/ is a sibling repo outside the Netlify build
 * context. NEVER wire this into prebuild. Run manually:
 *
 *     cd medikah-chat-frontend && npm run build:sogo-wave
 *
 * Then commit the regenerated wave.js in the superrepo.
 *
 * Source-of-truth: components/shared/practikah/Wave.tsx (which itself sources
 * fills from lib/design-tokens.ts). If you edit Wave.tsx geometry or fills,
 * rerun this script and commit wave.js — Vitest round-trip test in
 * scripts/build-sogo-wave.test.ts will catch staleness.
 */
import { renderToStaticMarkup } from 'react-dom/server';
import { writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import React from 'react';
import { Wave } from '../components/shared/practikah/Wave';
import { WAVE_VARIANTS } from '../components/shared/practikah/Wave.types';

// __dirname shim for tsx/ESM execution.
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const OUT = resolve(__dirname, '../../mailcow-config/sogo/wave.js');

// Pitfall 2 guard: fail loudly if the sibling repo isn't checked out.
// This will trigger on a fresh Netlify CI runner (good — we WANT CI to
// fail if anyone wires this into prebuild by mistake).
if (!existsSync(dirname(OUT))) {
  console.error(
    `[build-sogo-wave] mailcow-config/sogo/ not found at ${dirname(OUT)}.\n` +
      `This script is a LOCAL-ONLY build step. Check out the mailcow-config\n` +
      `sibling repo at ../mailcow-config/ and re-run. Do NOT add this to\n` +
      `npm prebuild — see RESEARCH Pitfall 2.`,
  );
  process.exit(1);
}

const rendered: Record<string, string> = {};
for (const variant of WAVE_VARIANTS) {
  rendered[variant] = renderToStaticMarkup(
    React.createElement(Wave, { variant }),
  );
}

const out =
  `/* AUTOGENERATED from medikah-chat-frontend/components/shared/practikah/Wave.tsx
 * Source-of-truth: medikah-chat-frontend/lib/design-tokens.ts.
 * Regenerated by: cd medikah-chat-frontend && npm run build:sogo-wave
 * Do NOT hand-edit. Commit this file in the mailcow-config repo.
 */
(function (w) {
  w.MK_WAVE_VARIANTS = ${JSON.stringify(rendered, null, 2)};
})(window);
`;

writeFileSync(OUT, out);
console.log(`✓ Wrote ${OUT} (${Object.keys(rendered).length} variants)`);
